import { describe, it, expect, vi, beforeEach } from 'vitest';

const { mockFormat } = vi.hoisted(() => ({
    mockFormat: vi.fn().mockReturnValue({
        text: 'Formatted response\n\n---\n<sub>Generated by CopilotKit AI</sub>',
        truncated: false,
    }),
}));

vi.mock('@copilotkit/outpost-ai', () => ({
    ResponseFormatter: class MockResponseFormatter {
        format = mockFormat;
    },
}));

vi.mock('@copilotkit/outpost-shared', () => ({
    AI_CONFIDENCE: {
        AUTO_RESPOND: 0.9,
        SUGGEST: 0.7,
        ESCALATE: 0.4,
    },
}));

vi.mock('../lib/github-client.js', () => ({
    postIssueComment: vi.fn().mockResolvedValue(12345),
    postDiscussionComment: vi.fn().mockResolvedValue('comment-id'),
}));

vi.mock('../config.js', () => ({
    config: {
        appId: 'test-app-id',
        privateKey: 'test-private-key',
        installationId: 'test-installation-id',
        webhookSecret: 'test-secret',
        port: 3200,
        teamLogins: [],
    },
}));

import { postAiResponse } from '../lib/github-poster.js';
import { postIssueComment, postDiscussionComment } from '../lib/github-client.js';

describe('postAiResponse', () => {
    beforeEach(() => {
        vi.clearAllMocks();
        // Reset the formatter mock for each test
        mockFormat.mockReturnValue({
            text: 'Formatted response\n\n---\n<sub>Generated by CopilotKit AI</sub>',
            truncated: false,
        });
    });

    it('posts formatted response as an issue comment', async () => {
        await postAiResponse(
            { kind: 'issue', issueNumber: 42 },
            {
                responseText: 'Here is the answer',
                confidence: 0.95,
                owner: 'CopilotKit',
                repo: 'CopilotKit',
            },
        );

        expect(postIssueComment).toHaveBeenCalledWith(
            'CopilotKit',
            'CopilotKit',
            42,
            expect.stringContaining('Was this helpful?'),
        );
    });

    it('posts formatted response as a discussion comment', async () => {
        await postAiResponse(
            { kind: 'discussion', discussionNodeId: 'D_kwDOTest1234' },
            {
                responseText: 'Here is the answer',
                confidence: 0.95,
                owner: 'CopilotKit',
                repo: 'CopilotKit',
            },
        );

        expect(postDiscussionComment).toHaveBeenCalledWith(
            'D_kwDOTest1234',
            expect.stringContaining('Was this helpful?'),
        );
    });

    it('adds disclaimer for low-confidence responses', async () => {
        // Re-mock format to verify the addDisclaimer option is passed
        mockFormat.mockReturnValue({
            text: 'Low confidence response',
            truncated: false,
        });

        // Re-import to pick up fresh formatter instance
        // Since the module was already imported, we call it directly
        // The mock is on the class constructor
        await postAiResponse(
            { kind: 'issue', issueNumber: 42 },
            {
                responseText: 'Not sure about this',
                confidence: 0.3,
                owner: 'CopilotKit',
                repo: 'CopilotKit',
            },
        );

        // The function should still post a comment (the formatter handles disclaimers)
        expect(postIssueComment).toHaveBeenCalled();
    });

    it('includes feedback section in the posted body', async () => {
        await postAiResponse(
            { kind: 'issue', issueNumber: 42 },
            {
                responseText: 'Answer text',
                confidence: 0.85,
                owner: 'CopilotKit',
                repo: 'CopilotKit',
            },
        );

        const callArgs = vi.mocked(postIssueComment).mock.calls[0];
        const body = callArgs[3];
        expect(body).toContain('Was this helpful?');
        expect(body).toContain('\uD83D\uDC4D');
        expect(body).toContain('\uD83D\uDC4E');
    });
});
