import type { FormattedResponse } from './types.js';
import type { PlatformTarget } from '@copilotkit/outpost/shared';

const DISCORD_MAX_LENGTH = 2000;

const STANDARD_FOOTER = '\n\n---\n*Powered by CopilotKit AI · [Docs](https://docs.copilotkit.ai) · Was this helpful? React with 👍 or 👎*';

const GITHUB_FOOTER = '\n\n---\n<sub>🤖 Generated by CopilotKit AI Support · [Documentation](https://docs.copilotkit.ai)</sub>';

const WEB_FOOTER = '\n\n---\n*Powered by CopilotKit AI*';

/**
 * Formats AI-generated responses for different platform targets.
 *
 * - Discord: markdown with 2000-char limit, splits into multiple messages, adds action buttons
 * - GitHub: full markdown with collapsible details sections
 * - Web: HTML-safe markdown
 */
export class ResponseFormatter {
    /**
     * Format a response for the specified platform.
     */
    format(
        text: string,
        platform: PlatformTarget,
        options?: { addDisclaimer?: boolean; disclaimerText?: string },
    ): FormattedResponse {
        const disclaimer = options?.addDisclaimer
            ? `> ⚠️ ${options.disclaimerText ?? 'This is an AI-generated response. A human agent will review shortly.'}\n\n`
            : '';

        const fullText = disclaimer + text;

        switch (platform) {
            case 'discord':
                return this.formatDiscord(fullText);
            case 'github':
                return this.formatGitHub(fullText);
            case 'slack':
            case 'teams':
            case 'web':
                return this.formatWeb(fullText);
        }
    }

    private formatDiscord(text: string): FormattedResponse {
        const withFooter = text + STANDARD_FOOTER;

        // Discord buttons metadata for the bot to attach
        const buttons = [
            { label: '👍 Helpful', action: 'feedback_positive' },
            { label: '👎 Not Helpful', action: 'feedback_negative' },
            { label: '🧑‍💻 Talk to Human', action: 'escalate' },
        ];

        if (withFooter.length <= DISCORD_MAX_LENGTH) {
            return {
                text: withFooter,
                buttons,
                truncated: false,
            };
        }

        // Split into multiple parts, preserving code blocks
        const parts = this.splitForDiscord(text);

        // Add footer only to the last part
        const lastIdx = parts.length - 1;
        parts[lastIdx] = parts[lastIdx] + STANDARD_FOOTER;

        // If even the last part is too long after footer, truncate it
        if (parts[lastIdx].length > DISCORD_MAX_LENGTH) {
            parts[lastIdx] = parts[lastIdx].slice(0, DISCORD_MAX_LENGTH - 3) + '...';
        }

        return {
            text: parts[0],
            parts,
            buttons,
            truncated: true,
        };
    }

    private splitForDiscord(text: string): string[] {
        const parts: string[] = [];
        // Reserve space for potential "... (continued)" markers
        const maxPartLength = DISCORD_MAX_LENGTH - 50;

        let remaining = text;
        while (remaining.length > 0) {
            if (remaining.length <= maxPartLength) {
                parts.push(remaining);
                break;
            }

            // Find a good split point: prefer paragraph breaks, then newlines, then spaces
            let splitAt = maxPartLength;

            const paragraphBreak = remaining.lastIndexOf('\n\n', maxPartLength);
            if (paragraphBreak > maxPartLength * 0.5) {
                splitAt = paragraphBreak;
            } else {
                const lineBreak = remaining.lastIndexOf('\n', maxPartLength);
                if (lineBreak > maxPartLength * 0.5) {
                    splitAt = lineBreak;
                } else {
                    const space = remaining.lastIndexOf(' ', maxPartLength);
                    if (space > maxPartLength * 0.5) {
                        splitAt = space;
                    }
                }
            }

            // Check if we're splitting inside a code block
            const part = remaining.slice(0, splitAt);
            const openFences = (part.match(/```/g) || []).length;
            if (openFences % 2 !== 0) {
                // We're inside a code block — close it and reopen in next part
                parts.push(part + '\n```');
                remaining = '```\n' + remaining.slice(splitAt).trimStart();
            } else {
                parts.push(part);
                remaining = remaining.slice(splitAt).trimStart();
            }
        }

        return parts;
    }

    private formatGitHub(text: string): FormattedResponse {
        // Wrap long code blocks in collapsible details
        const formatted = text.replace(
            /```(\w+)?\n([\s\S]{500,}?)```/g,
            (match, lang, code) => {
                const langLabel = lang ? ` (${lang})` : '';
                return `<details><summary>Code example${langLabel}</summary>\n\n\`\`\`${lang ?? ''}\n${code}\`\`\`\n</details>`;
            },
        );

        return {
            text: formatted + GITHUB_FOOTER,
            truncated: false,
        };
    }

    private formatWeb(text: string): FormattedResponse {
        // For web, ensure markdown is clean and HTML-safe
        // Escape any raw HTML that isn't part of markdown
        const sanitized = text
            .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
            .replace(/<iframe\b[^<]*(?:(?!<\/iframe>)<[^<]*)*<\/iframe>/gi, '')
            .replace(/on\w+="[^"]*"/gi, '');

        return {
            text: sanitized + WEB_FOOTER,
            truncated: false,
        };
    }
}
